name: Update Packagist

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        run: |
          curl -X POST \
            -d '{"repository":{"url":"https://github.com/amiralishabani/aash-captcha"}}' \
            -H "Content-Type: application/json" \
            https://packagist.org/api/update-package?username=amiralishabani&apiToken=${{ secrets.97c534c54f033d705060bfe3ce8f7ac2419e71ba }}
